/* ************************************************************************** */
/*                                                                            */
/*                                                        :::      ::::::::   */
/*   main.c                                             :+:      :+:    :+:   */
/*                                                    +:+ +:+         +:+     */
/*   By: gsharony <gsharony@student.42.fr>          +#+  +:+       +#+        */
/*                                                +#+#+#+#+#+   +#+           */
/*   Created: 2019/10/22 10:20:28 by gsharony          #+#    #+#             */
/*   Updated: 2019/11/04 12:07:08 by gsharony         ###   ########.fr       */
/*                                                                            */
/* ************************************************************************** */

#include "ft_printf.h"
#include <stdio.h>

void	ft_check(int a, int b)
{
	if (a == b)
		printf("\033[1;32m[%d] - [%d]\033[0m\n\n", a, b);
	else
		printf("\033[1;31m[%d] - [%d]\033[0m\n\n", a, b);
}

int		main(void)
{
	int		a;
	int		b;
	int		c;
	int		d;

	a = -42;
	printf("\n___ Testing [simple output] ___\n");
	c = ft_printf(">---|%%|\n");
	d = printf("<---|%%|\n");
	ft_check(c, d);
	c = ft_printf(">---|%%%%|\n");
	d = printf("<---|%%%%|\n");
	ft_check(c, d);

	printf("\n___ Testing [%%c] ___ \n");
	c = ft_printf(">---|%c|\n", 'a');
	d = printf("<---|%c|\n", 'a');
	ft_check(c, d);
	c = ft_printf(">---|%c|\n", '\0');
	d = printf("<---|%c|\n", '\0');
	ft_check(c, d);
	c = ft_printf(">---|%c|\n", (char)0xff11ff11);
	d = printf("<---|%c|\n", (char)0xff11ff11);
	ft_check(c, d);
	c = ft_printf(">---|%c|\n", -21);
	d = printf("<---|%c|\n", -21);
	ft_check(c, d);
	c = ft_printf(">---|%4c|\n", 'U');
	d = printf("<---|%4c|\n", 'U');
	ft_check(c, d);
	c = ft_printf(">---|%-1c|\n", 12);
	d = printf("<---|%-1c|\n", 12);
	ft_check(c, d);
	c = ft_printf(">---|%-12c|\n", '\n');
	d = printf("<---|%-12c|\n", '\n');
	ft_check(c, d);
	c = ft_printf(">---|hello ca%----4c %1c va %10c%-c ??|\n", '\0', '\n', (char)564, 0);
	d = printf("<---|hello ca%----4c %1c va %10c%-c ??|\n", '\0', '\n', (char)564, 0);
	ft_check(c, d);

	printf("\n___ Testing [%%s] ___\n");
	c = ft_printf(">---|%s|\n", NULL);
	d = printf("<---|%s|\n", NULL);
	ft_check(c, d);
	c = ft_printf(">---|%s|\n", "coco");
	d = printf("<---|%s|\n", "coco");
	ft_check(c, d);
	c = ft_printf(">---|%s|\n", "");
	d = printf("<---|%s|\n", "");
	ft_check(c, d);
	c = ft_printf(">---|%.15s|\n", "coco");
	d = printf("<---|%.15s|\n", "coco");
	ft_check(c, d);
	c = ft_printf(">---|%.5s|\n", "coco et titi");
	d = printf("<---|%.5s|\n", "coco et titi");
	ft_check(c, d);
	c = ft_printf(">---|%.0s|\n", "coco et ti");
	d = printf("<---|%.0s|\n", "coco et ti");
	ft_check(c, d);
	c = ft_printf(">---|%.s|\n", "coco");
	d = printf("<---|%.s|\n", "coco");
	ft_check(c, d);
	c = ft_printf(">---|%.2s|\n", NULL);
	d = printf("<---|%.2s|\n", NULL);
	ft_check(c, d);
	c = ft_printf(">---|%10s|\n", NULL);
	d = printf("<---|%10s|\n", NULL);
	ft_check(c, d);
	c = ft_printf(">---|%-8s|\n", "coco");
	d = printf("<---|%-8s|\n", "coco");
	ft_check(c, d);
	c = ft_printf(">---|%1s|\n", "hi");
	d = printf("<---|%1s|\n", "hi");
	ft_check(c, d);
	c = ft_printf(">---|%-2s|\n", "");
	d = printf("<---|%-2s|\n", "");
	ft_check(c, d);
	c = ft_printf(">---|Coucou %.0s\n%s%---12s|\n", "hi", "coco", NULL);
	d = printf("<---|Coucou %.0s\n%s%---12s|\n", "hi", "coco", NULL);
	ft_check(c, d);
	c = ft_printf(">---|u%4.2ss %-1.s\n %---5.3s|\n", "coco", NULL, "yooo");
	d = printf("<---|u%4.2ss %-1.s\n %---5.3s|\n", "coco", NULL, "yooo");
	ft_check(c, d);
	c = ft_printf(">---|%1.4s et %-6.8s et %4.2s|\n", "tuuu", "12345", "hu");
	d = printf("<---|%1.4s et %-6.8s et %4.2s|\n", "tuuu", "12345", "hu");
	ft_check(c, d);

	printf("\n___ Testing [%%p] ___\n");
	c = ft_printf(">---|%p|\n", NULL);
	d = printf("<---|%p|\n", NULL);
	ft_check(c, d);
	c = ft_printf(">---|%p|\n", &a);
	d = printf("<---|%p|\n", &a);
	ft_check(c, d);
	c = ft_printf(">---|%20p|\n", &a);
	d = printf("<---|%20p|\n", &a);
	ft_check(c, d);
	c = ft_printf(">---|%-25p|\n", &a);
	d = printf("<---|%-25p|\n", &a);
	ft_check(c, d);
	c = ft_printf(">---|%2p|\n", &a);
	d = printf("<---|%2p|\n", &a);
	ft_check(c, d);
	c = ft_printf(">---|%----24p et hello %2p %12p|\n", &b, &a, NULL);
	d = printf("<---|%----24p et hello %2p %12p|\n", &b, &a, NULL);
	ft_check(c, d);

	printf("\n___ Testing [%%d] ___\n");
	c = ft_printf(">---|%d|\n", 42);
	d = printf("<---|%d|\n", 42);
	ft_check(c, d);
	c = ft_printf(">---|%d|\n", -42);
	d = printf("<---|%d|\n", -42);
	ft_check(c, d);
	c = ft_printf(">---|%d|\n", 0);
	d = printf("<---|%d|\n", 0);
	ft_check(c, d);
	c = ft_printf(">---|%d|\n", 3);
	d = printf("<---|%d|\n", 3);
	ft_check(c, d);
	c = ft_printf(">---|%d|\n", -2147483647);
	d = printf("<---|%d|\n", -2147483647);
	ft_check(c, d);
	c = ft_printf(">---|%d|\n", 0);
	d = printf("<---|%d|\n", 0);
	ft_check(c, d);
	c = ft_printf(">---|%+d|\n", 0);
	d = printf("<---|%+d|\n", 0);
	ft_check(c, d);
	c = ft_printf(">---|%+++d|\n", 534);
	d = printf("<---|%+++d|\n", 534);
	ft_check(c, d);
	c = ft_printf(">---|% d|\n", 0xff11ff);
	d = printf("<---|% d|\n", 0xff11ff);
	ft_check(c, d);
	c = ft_printf(">---|%.2d|\n", 1144);
	d = printf("<---|%.2d|\n", 1144);
	ft_check(c, d);
	c = ft_printf(">---|%.d|\n", 0);
	d = printf("<---|%.d|\n", 0);
	ft_check(c, d);
	c = ft_printf(">---|%-7d|\n", 7789);
	d = printf("<---|%-7d|\n", 7789);
	ft_check(c, d);
	c = ft_printf(">---|%0d|\n", -579);
	d = printf("<---|%0d|\n", -579);
	ft_check(c, d);
	c = ft_printf(">---|%04d|\n", 0);
	d = printf("<---|%04d|\n", 0);
	ft_check(c, d);
	c = ft_printf(">---|%+12.5d|\n", 140);
	d = printf("<---|%+12.5d|\n", 140);
	ft_check(c, d);
	c = ft_printf(">---|%00+10.4d|\n", 0);
	d = printf("<---|%00+10.4d|\n", 0);
	ft_check(c, d);
	c = ft_printf(">---|%.0d|\n", -21);
	d = printf("<---|%.0d|\n", -21);
	ft_check(c, d);
	c = ft_printf(">---|%.5d|\n", -421);
	d = printf("<---|%.5d|\n", -421);
	ft_check(c, d);
	c = ft_printf(">---|%5d|\n", -741);
	d = printf("<---|%5d|\n", -741);
	ft_check(c, d);
	c = ft_printf(">---|hello % .d this is a test|\n", 0);
	d = printf("<---|hello % .d this is a test|\n", 0);
	ft_check(c, d);

	printf("\n___ Testing [%%i] ___\n");
	c = ft_printf(">---|%i|\n", (signed int)0xff11);
	d = printf("<---|%i|\n", (signed int)0xff11);
	ft_check(c, d);
	c = ft_printf(">---|%.2i|\n", -10);
	d = printf("<---|%.2i|\n", -10);
	ft_check(c, d);
	c = ft_printf(">---|%.i|\n", 44);
	d = printf("<---|%.i|\n", 44);
	ft_check(c, d);
	c = ft_printf(">---|%08i|\n", -71);
	d = printf("<---|%08i|\n", -71);
	ft_check(c, d);
	c = ft_printf(">---|%-2i|\n", -7);
	d = printf("<---|%-2i|\n", -7);
	ft_check(c, d);
	c = ft_printf(">---|%.0i|\n", 0);
	d = printf("<---|%.0i|\n", 0);
	ft_check(c, d);

	printf("\n___ Testing [%%u] ___\n");
	c = ft_printf(">---|%u|\n", 0);
	d = printf("<---|%u|\n", 0);
	ft_check(c, d);
	c = ft_printf(">---|%u|\n", 1234);
	d = printf("<---|%u|\n", 1234);
	ft_check(c, d);
	c = ft_printf(">---|%u|\n", -1001234);
	d = printf("<---|%u|\n", -1001234);
	ft_check(c, d);
	c = ft_printf(">---|%.1u|\n", 121);
	d = printf("<---|%.1u|\n", 121);
	ft_check(c, d);
	c = ft_printf(">---|%.0u|\n", 76543);
	d = printf("<---|%.0u|\n", 76543);
	ft_check(c, d);
	c = ft_printf(">---|%.u|\n", -7);
	d = printf("<---|%.u|\n", -7);
	ft_check(c, d);
	c = ft_printf(">---|%4u|\n", 1);
	d = printf("<---|%4u|\n", 1);
	ft_check(c, d);
	c = ft_printf(">---|%-12u|\n", 17894);
	d = printf("<---|%-12u|\n", 17894);
	ft_check(c, d);
	c = ft_printf(">---|%2u|\n", 17894);
	d = printf("<---|%2u|\n", 17894);
	ft_check(c, d);
	c = ft_printf(">---|%08u|\n", 171894);
	d = printf("<---|%08u|\n", 171894);
	ft_check(c, d);
	c = ft_printf(">---|%0u|\n", 194);
	d = printf("<---|%0u|\n", 194);
	ft_check(c, d);
	c = ft_printf(">---|%-3u|\n", 194);
	d = printf("<---|%-3u|\n", 194);
	ft_check(c, d);
	c = ft_printf(">---|toto et %02u coco %-5u mimi|\n", 19, -20);
	d = printf("<---|toto et %02u coco %-5u mimi|\n", 19, -20);
	ft_check(c, d);
	c = ft_printf(">---|\ntoto et %00009u%-2u mimi et titi%--14u|\n", 0, 14, 200);
	d = printf("<---|\ntoto et %00009u%-2u mimi et titi%--14u|\n", 0, 14, 200);
	ft_check(c, d);
	c = ft_printf(">---|ko%-4.2u et %05.2u!|\n", -456, 0);
	d = printf("<---|ko%-4.2u et %05.2u!|\n", -456, 0);
	ft_check(c, d);
	c = ft_printf(">---|%05.1u %3.4u %-4.7u|\n", 45, -1789, 147);
	d = printf("<---|%05.1u %3.4u %-4.7u|\n", 45, -1789, 147);
	ft_check(c, d);
	c = ft_printf(">---|%.u|\n", 0);
	d = printf("<---|%.u|\n", 0);
	ft_check(c, d);

	printf("\n___ Testing [%%x & %%X] ___\n");
	c = ft_printf(">---|%x|\n", 0);
	d = printf("<---|%x|\n", 0);
	ft_check(c, d);
	c = ft_printf(">---|%X|\n", 0xa0);
	d = printf("<---|%X|\n", 0xa0);
	ft_check(c, d);
	c = ft_printf(">---|%x|\n", 0xa0ffff);
	d = printf("<---|%x|\n", 0xa0ffff);
	ft_check(c, d);
	c = ft_printf(">---|%x|\n", -12345678);
	d = printf("<---|%x|\n", -12345678);
	ft_check(c, d);
	c = ft_printf(">---|%X|\n", 0);
	d = printf("<---|%X|\n", 0);
	ft_check(c, d);
	c = ft_printf(">---|%x|\n", 0x78aa);
	d = printf("<---|%x|\n", 0x78aa);
	ft_check(c, d);
	c = ft_printf(">---|%X|\n", 0xff7744);
	d = printf("<---|%X|\n", 0xff7744);
	ft_check(c, d);
	c = ft_printf(">---|%.x|\n", 12);
	d = printf("<---|%.x|\n", 12);
	ft_check(c, d);
	c = ft_printf(">---|%.0X|\n", 0xaabbcc);
	d = printf("<---|%.0X|\n", 0xaabbcc);
	ft_check(c, d);
	c = ft_printf(">---|%.2X|\n", 0x11aabbcc);
	d = printf("<---|%.2X|\n", 0x11aabbcc);
	ft_check(c, d);
	c = ft_printf(">---|%.10x|\n", 0x1234abcd);
	d = printf("<---|%.10x|\n", 0x1234abcd);
	ft_check(c, d);
	c = ft_printf(">---|%.4x|\n", 0x78);
	d = printf("<---|%.4x|\n", 0x78);
	ft_check(c, d);
	c = ft_printf(">---|%3x|\n", 0xa43);
	d = printf("<---|%3x|\n", 0xa43);
	ft_check(c, d);
	c = ft_printf(">---|%1X|\n", 0xa3);
	d = printf("<---|%1X|\n", 0xa3);
	ft_check(c, d);
	c = ft_printf(">---|%4x|\n", 0xdd);
	d = printf("<---|%4x|\n", 0xdd);
	ft_check(c, d);
	c = ft_printf(">---|%011X|\n", 0xdd66);
	d = printf("<---|%011X|\n", 0xdd66);
	ft_check(c, d);
	c = ft_printf(">---|%-6x|\n", 0xdd66);
	d = printf("<---|%-6x|\n", 0xdd66);
	ft_check(c, d);
	c = ft_printf(">---|%-2x|\n", 0xadd66);
	d = printf("<---|%-2x|\n", 0xadd66);
	ft_check(c, d);
	c = ft_printf(">---|%20x|\n", 0x123456bc);
	d = printf("<---|%20x|\n", 0x123456bc);
	ft_check(c, d);
	c = ft_printf(">---|test%---10.6x et %01X !!\n|\n", 0xaabb, 0);
	d = printf("<---|test%---10.6x et %01X !!\n|\n", 0xaabb, 0);
	ft_check(c, d);
	c = ft_printf(">---|t %7.5X%0006.2x!|\n", 0xab, 0x876);
	d = printf("<---|t %7.5X%0006.2x!|\n", 0xab, 0x876);
	ft_check(c, d);
	c = ft_printf(">---|toto %00.4X%4.2xet c'est fini \n|\n", 0x037a, 0x9e);
	d = printf("<---|toto %00.4X%4.2xet c'est fini \n|\n", 0x037a, 0x9e);
	ft_check(c, d);
	c = ft_printf(">---|cc%.4X et %0012x %04X !!|\n", 0xaef, 0xe, 0);
	d = printf("<---|cc%.4X et %0012x %04X !!|\n", 0xaef, 0xe, 0);
	ft_check(c, d);
	return (0);
}
